# ===============================
#   Starship Prompt Config  ğŸš€
# ===============================

"$schema" = 'https://starship.rs/config-schema.json'

# Disable the newline at the start of the prompt
add_newline = false
# Wait 20 milliseconds for starship to check files under the current directory.
scan_timeout = 20
format = """\
  $username\
  ${custom.host}\
  $all\
  $time\
  $line_break\
  $character\
"""
  # $fill\

[character]
success_symbol = "[â¯](bold)"
error_symbol = "[â¯](bold red)"
vicmd_symbol = "[â®](bold)"
# bellow config fish only
vimcmd_replace_one_symbol = "[â®](bold purple)"
vimcmd_replace_symbol = "[â®](bold purple)"
vimcmd_visual_symbol = "[â®](bold yellow)"

[fill]
symbol = " "

[username]
show_always = false
style_user = "bold yellow"
style_root = "bold red"

[hostname]
ssh_only = true
style = "bold blue"
ssh_symbol = "ó°–Ÿ "
disabled = true

[custom.host]
command = 'echo "${OS_ICON}$(hostname -s)"'
# command = 'echo "${OS_ICON}"'
when = 'test -n "${SSH_CONNECTION}"'
format = "[$output]($style) in "
style = "bold blue"
shell = ["/bin/bash", "--norc"]
disabled = false

[directory]
style = "bold cyan"
# format = "in [$path]($style)[$read_only]($read_only_style) "

# ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªéšå±¤ãŒä¸€å®šä»¥ä¸Šã«ãªã£ãŸå ´åˆã«ä¸Šä½ã®ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªã‚’çŸ­ç¸®ã™ã‚‹
truncation_length = 3
# ãƒªãƒã‚¸ãƒˆãƒªã‚ˆã‚Šä¸Šä½ã®ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªã‚’çŸ­ç¸®ã™ã‚‹
truncate_to_repo = true
# çŸ­ç¸®ã•ã‚ŒãŸæ™‚ã®æ–‡å­—æ•°
fish_style_pwd_dir_length = 1

read_only = " ï€£"
read_only_style = "yellow"
# i_fa.sh:41:i='ï€£' i_fa_lock=$i
# i_fa.sh:165:i='ï‚œ' i_fa_unlock=$i
# i_fa.sh:325:i='ï„¾' i_fa_unlock_alt=$i


[time]
disabled = true
use_12hr = false
time_format = "%T"
# style = "bold yellow"
style = "bright-black"
format = '[$time]($style) '

[cmd_duration]
disabled = true

[shell]
disabled = false
style = "white"
# ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã‚·ã‚§ãƒ«ã¨é•ã†ã¨ãã ã‘è¡¨ç¤º
bash_indicator="îª… bash"
fish_indicator="îª… fish"
zsh_indicator=""
# îª…   i_cod_terminal
# î•   i_dev_terminal
# ï’‰   i_oct_terminal


[direnv]
format = "[$symbol$loaded$allowed]($style) "
disabled = false
# ã‚¨ãƒ©ãƒ¼ã®æ™‚ã ã‘è¡¨ç¤º
loaded_msg = ""
unloaded_msg = "not loaded"
allowed_msg = ""
not_allowed_msg = " not allowed"
denied_msg = " denied"

[git_commit]
tag_symbol = "ï€« "
tag_disabled = true
only_detached = true

[git_status]
disabled = false

[c]
# symbol = "î˜ "
symbol = "î™‰ "

[nodejs]
# symbol = "â¬¢ "
detect_extensions = ["js", "mjs", "cjs", "ts", "mts", "cts", "jsx", "tsx"]
symbol = "îœ˜ "
style = "bold green"

[deno]
symbol = "îŸ€ "

[rust]
symbol = "îš‹ "
style = "bold 172"
# style = "bold 166"

[golang]
# symbol = "î˜¦ "
symbol = "î˜§ "
style = "bold cyan"

[python]
symbol = "î˜† "
pyenv_version_name = false
style = "bold yellow"
# detect_extensions = ["py", "ipynb"]
detect_extensions = ["py"]

[ruby]
symbol = "î˜… "
style = "bold 166"

[java]
#symbol = "î˜› "
symbol = "î™­ "
style = "bold 166"

[kotlin]
symbol = "î˜´ "

[gradle]
symbol = "î™  "

[scala]
symbol = "îš "

[php]
symbol = "î˜ˆ "
style = "bold 109"

[perl]
symbol = "î™¾ "

[dart]
symbol = "î™Œ "

[elm]
symbol = "î˜¬ "

[elixir]
symbol = "î˜­ "
# detect_extensions = ["exs"]

[haskell]
symbol = "î˜Ÿ "

[julia]
symbol = "î˜¤ "

[nim]
symbol = "î™· "

[rlang]
symbol = "îšŠ "

[package]
symbol = "î¬© "
disabled = true

[gcloud]
disabled = true

[vagrant]
format = "via [$symbol]($style)"
symbol = "îš¬ "
disabled = false

[kubernetes]
symbol = "ó±ƒ¾ "

[docker_context]
# symbol = "î™ " # seti
symbol = "ïŒˆ " # logo

[cmake]
symbol = "î™³ "

[lua]
symbol = "î˜  "

# Devicons
# îœ€  îœ  îœ‚  îœƒ  îœ„  îœ…  îœ†  îœ‡  îœˆ  îœ‰  îœŠ  îœ‹  îœŒ  îœ  îœ  îœ
# îœ  îœ‘  îœ’  îœ“  îœ”  îœ•  îœ–  îœ—  îœ˜  îœ™  îœš  îœ›  îœœ  îœ  îœ  îœŸ
# îœ   îœ¡  îœ¢  îœ£  îœ¤  îœ¥  îœ¦  îœ§  îœ¨  îœ©  îœª  îœ«  îœ¬  îœ­  îœ®  îœ¯
# îœ°  îœ±  îœ²  îœ³  îœ´  îœµ  îœ¶  îœ·  îœ¸  îœ¹  îœº  îœ»  îœ¼  îœ½  îœ¾  îœ¿
# î€  î  î‚  îƒ  î„  î…  î†  î‡  îˆ  î‰  îŠ  î‹  îŒ  î  î  î
# î  î‘  î’  î“  î”  î•  î–  î—  î˜  î™  îš  î›  îœ  î  î  îŸ
# î   î¡  î¢  î£  î¤  î¥  î¦  î§  î¨  î©  îª  î«  î¬  î­  î®  î¯
# î°  î±  î²  î³  î´  îµ  î¶  î·  î¸  î¹  îº  î»  î¼  î½  î¾  î¿
# î€  î  î‚  îƒ  î„  î…  î†  î‡  îˆ  î‰  îŠ  î‹  îŒ  î  î  î
# î  î‘  î’  î“  î”  î•  î–  î—  î˜  î™  îš  î›  îœ  î  î  îŸ
# î   î¡  î¢  î£  î¤  î¥  î¦  î§  î¨  î©  îª  î«  î¬  î­  î®  î¯
# î°  î±  î²  î³  î´  îµ  î¶  î·  î¸  î¹  îº  î»  î¼  î½  î¾  î¿
# îŸ€  îŸ  îŸ‚  îŸƒ  îŸ„  îŸ…

# Seti-UI Cusotom
# î—º  î—»  î—¼  î—½  î—¾  î—¿
# î˜€  î˜  î˜‚  î˜ƒ  î˜„  î˜…  î˜†  î˜‡  î˜ˆ  î˜‰  î˜Š  î˜‹  î˜Œ  î˜  î˜  î˜
# î˜  î˜‘  î˜’  î˜“  î˜”  î˜•  î˜–  î˜—  î˜˜  î˜™  î˜š  î˜›  î˜œ  î˜  î˜  î˜Ÿ
# î˜   î˜¡  î˜¢  î˜£  î˜¤  î˜¥  î˜¦  î˜§  î˜¨  î˜©  î˜ª  î˜«  î˜¬  î˜­  î˜®  î˜¯
# î˜°  î˜±  î˜²  î˜³  î˜´  î˜µ  î˜¶  î˜·  î˜¸  î˜¹  î˜º  î˜»  î˜¼  î˜½  î˜¾  î˜¿
# î™€  î™  î™‚  î™ƒ  î™„  î™…  î™†  î™‡  î™ˆ  î™‰  î™Š  î™‹  î™Œ  î™  î™  î™
# î™  î™‘  î™’  î™“  î™”  î™•  î™–  î™—  î™˜  î™™  î™š  î™›  î™œ  î™  î™  î™Ÿ
# î™   î™¡  î™¢  î™£  î™¤  î™¥  î™¦  î™§  î™¨  î™©  î™ª  î™«  î™¬  î™­  î™®  î™¯
# î™°  î™±  î™²  î™³  î™´  î™µ  î™¶  î™·  î™¸  î™¹  î™º  î™»  î™¼  î™½  î™¾  î™¿
# îš€  îš  îš‚  îšƒ  îš„  îš…  îš†  îš‡  îšˆ  îš‰  îšŠ  îš‹  îšŒ  îš  îš  îš
# îš  îš‘  îš’  îš“  îš”  îš•  îš–  îš—  îš˜  îš™  îšš  îš›  îšœ  îš  îš  îšŸ
# îš   îš¡  îš¢  îš£  îš¤  îš¥  îš¦  îš§  îš¨  îš©  îšª  îš«  îš¬


[os]
# format = "[$symbol]($style)"
# format = "on [($name )]($style)"
format = "on [$symbol]($style)"
disabled = true

[os.symbols]
# ïŒ€  ïŒ  ïŒ‚  ïŒƒ  ïŒ„  ïŒ…  ïŒ†  ïŒ‡  ïŒˆ  ïŒ‰  ïŒŠ  ïŒ‹  ïŒŒ  ïŒ  ïŒ  ïŒ
# ïŒ  ïŒ‘  ïŒ’  ïŒ“  ïŒ”  ïŒ•  ïŒ–  ïŒ—  ïŒ˜  ïŒ™  ïŒš  ïŒ›  ïŒœ  ïŒ  ïŒ  ïŒŸ
# ïŒ   ïŒ¡  ïŒ¢  ïŒ£  ïŒ¤  ïŒ¥  ïŒ¦  ïŒ§  ïŒ¨  ïŒ©  ïŒª  ïŒ«  ïŒ¬  ïŒ­  ïŒ®  ïŒ¯
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "       # logoã«ãªã„
Android = "ï…» "      # logoã«ãªã„
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
EndeavourOS = "ïŒ¢ "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ïŒ· "
Gentoo = "ïŒ "
Illumos = "ïŒ¦ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mint = "ïŒ "
NixOS = "ïŒ“ "
Nobara = "ï€ "
OpenBSD = "ïŒ¨ "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· " # logoã«ãªã„
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Solus = "ïŒ­ "
SUSE = "ïŒ” "
Ubuntu = "ïŒœ "
Void = "ïŒ® "
Windows = "îœ "


# preset [ner-dont-symbols]
# [os.symbols]
# Alpaquita = "îª¢ "
# Alpine = "ïŒ€ "
# AlmaLinux = "ïŒ "
# Amazon = "ï‰° "
# Android = "ï…» "
# Arch = "ïŒƒ "
# Artix = "ïŒŸ "
# CachyOS = "ïŒƒ "
# CentOS = "ïŒ„ "
# Debian = "ïŒ† "
# DragonFly = "îŠ "
# Emscripten = "ïˆ… "
# EndeavourOS = "ï†— "
# Fedora = "ïŒŠ "
# FreeBSD = "ïŒŒ "
# Garuda = "ó°›“ "
# Gentoo = "ïŒ "
# HardenedBSD = "ó°Œ "
# Illumos = "ó°ˆ¸ "
# Kali = "ïŒ§ "
# Linux = "ïŒš "
# Mabox = "î¬© "
# Macos = "ïŒ‚ "
# Manjaro = "ïŒ’ "
# Mariner = "ï‡ "
# MidnightBSD = "ï†† "
# Mint = "ïŒ "
# NetBSD = "ï€¤ "
# NixOS = "ïŒ“ "
# Nobara = "ï€ "
# OpenBSD = "ó°ˆº "
# openSUSE = "ïŒ” "
# OracleLinux = "ó°Œ· "
# Pop = "ïŒª "
# Raspbian = "ïŒ• "
# Redhat = "ïŒ– "
# RedHatEnterprise = "ïŒ– "
# RockyLinux = "ïŒ« "
# Redox = "ó°€˜ "
# Solus = "ó° ³ "
# SUSE = "ïŒ” "
# Ubuntu = "ïŒ› "
# Unknown = "ïˆ­ "
# Void = "ïŒ® "
# Windows = "ó°² "


